### ISSUE TITLE
ValueError: numpy.ufunc has the wrong size, try recompiling. Expected 192

### ISSUE THREAD

**Issue by iamlxb3** [thunlp/OpenNE#85] opened 2019-09-19 12:09 UTC
Python version: 3.6.7

I install all requirements after creating a conda environment.

But something went wrong when I ran "python -m openne --help"

Traceback (most recent call last):
  File "/Users/jiashupu/miniconda3/envs/openne/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/jiashupu/miniconda3/envs/openne/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/jiashupu/playground/python/OpenNE/src/openne/__main__.py", line 9, in <module>
    from . import line
  File "/Users/jiashupu/playground/python/OpenNE/src/openne/line.py", line 6, in <module>
    import tensorflow as tf
  File "/Users/jiashupu/miniconda3/envs/general/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/Users/jiashupu/miniconda3/envs/general/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 84, in <module>
    from tensorflow.python.framework.framework_lib import *
  File "/Users/jiashupu/miniconda3/envs/general/lib/python3.6/site-packages/tensorflow/python/framework/framework_lib.py", line 78, in <module>
    from tensorflow.python.framework.sparse_tensor import SparseTensor
  File "/Users/jiashupu/miniconda3/envs/general/lib/python3.6/site-packages/tensorflow/python/framework/sparse_tensor.py", line 25, in <module>
    from tensorflow.python.framework import tensor_util
  File "/Users/jiashupu/miniconda3/envs/general/lib/python3.6/site-packages/tensorflow/python/framework/tensor_util.py", line 33, in <module>
    from tensorflow.python.framework import fast_tensor_util
  File "__init__.pxd", line 872, in init tensorflow.python.framework.fast_tensor_util
ValueError: numpy.ufunc has the wrong size, try recompiling. Expected 192, got 216 

---

installed package:
packages in environment at /Users/jiashupu/miniconda3/envs/openne:

 Name                    Version                   Build  Channel
absl-py                   0.8.0                    py36_0    conda-forge
asn1crypto                0.24.0                py36_1003    conda-forge
astor                     0.7.1                      py_0    conda-forge
blas                      1.1                    openblas    conda-forge
boto                      2.49.0                     py_0    conda-forge
boto3                     1.9.231                    py_0    conda-forge
botocore                  1.12.231                   py_0    conda-forge
bz2file                   0.98                       py_0    conda-forge
c-ares                    1.15.0            h01d97ff_1001    conda-forge
ca-certificates           2019.9.11            hecc5488_0    conda-forge
certifi                   2019.6.16                py36_1    conda-forge
cffi                      1.12.3           py36hccf1714_0    conda-forge
chardet                   3.0.4                 py36_1003    conda-forge
cryptography              2.7              py36h212c5bf_0    conda-forge
decorator                 4.4.0                      py_0    conda-forge
docutils                  0.15.2                   py36_0    conda-forge
gast                      0.3.2                      py_0    conda-forge
gensim                    3.0.1                    pypi_0    pypi
grpcio                    1.23.0           py36h6ef0057_0    conda-forge
h5py                      2.9.0           nompi_py36h35dc34b_1102    conda-forge
hdf5                      1.10.4          nompi_h0cbb7df_1106    conda-forge
idna                      2.8                   py36_1000    conda-forge
intel-openmp              2019.4                      233  
jmespath                  0.9.4                      py_0    conda-forge
keras-applications        1.0.8                      py_1    conda-forge
keras-preprocessing       1.1.0                      py_0    conda-forge
libcxx                    8.0.1                         0    conda-forge
libcxxabi                 8.0.1                         0    conda-forge
libffi                    3.2.1             h6de7cb9_1006    conda-forge
libgfortran               3.0.1                         0    conda-forge
libopenblas               0.2.20               hdc02c5d_7  
libprotobuf               3.9.1                hfbae3c0_0    conda-forge
markdown                  3.1.1                      py_0    conda-forge
mkl                       2018.0.3                      1  
mock                      3.0.5                    py36_0    conda-forge
ncurses                   6.1               h0a44026_1002    conda-forge
networkx                  2.0                      pypi_0    pypi
numpy                     1.14.0                   pypi_0    pypi
openblas                  0.2.20                        8    conda-forge
openne                    0.0.0                    pypi_0    pypi
openssl                   1.1.1c               h01d97ff_0    conda-forge
pip                       19.2.3                   py36_0    conda-forge
protobuf                  3.9.1            py36h6de7cb9_0    conda-forge
pycparser                 2.19                     py36_1    conda-forge
pyopenssl                 19.0.0                   py36_0    conda-forge
pysocks                   1.7.0                    py36_0    conda-forge
python                    3.6.7             h94afb7f_1005    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge
readline                  8.0                  hcfe32e1_0    conda-forge
requests                  2.22.0                   py36_1    conda-forge
s3transfer                0.2.1                    py36_0    conda-forge
scikit-learn              0.19.0                   pypi_0    pypi
scipy                     0.19.1                   pypi_0    pypi
setuptools                41.2.0                   py36_0    conda-forge
six                       1.12.0                py36_1000    conda-forge
smart_open                1.8.4                      py_0    conda-forge
sqlite                    3.29.0               hb7d70f7_1    conda-forge
tensorboard               1.13.1                   py36_0    conda-forge
tensorflow                1.13.1                   py36_1    conda-forge
tensorflow-estimator      1.13.0                     py_0  
termcolor                 1.1.0                      py_2    conda-forge
tk                        8.6.9             h2573ce8_1003    conda-forge
urllib3                   1.25.3                   py36_0    conda-forge
werkzeug                  0.15.6                     py_0    conda-forge
wheel                     0.33.6                   py36_0    conda-forge
xz                        5.2.4             h1de35cc_1001    conda-forge
zlib                      1.2.11            h01d97ff_1006    conda-forge

**Comment by holacola1985** [comment] 2019-09-29 08:07
Duplicate of #71

**Closed as completed** 2020-08-01 03:20 UTC
